name: dbas_filesystem
description: "Flutter plugin for cross-platform file system operations with streaming, byte array, and directory support across Android, iOS, macOS, Linux, Windows, and Web (OPFS)."
version: 2.0.1
homepage: https://github.com/dailysoftwaresystems/DBAS.FileSystem.Dart
author_name: Daily Software Systems
author_email: dailysoftwaresystems@dailysoftwaresystems.com

environment:
  sdk: ^3.11.1
  flutter: '>=3.41.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DbasFileSystemNativeWeb
        fileName: src/native/dbas_filesystem_native_web.dart
  assets:
    - web/libs/dbas_filesystem_worker.js
